name: CITS-Continous Testing
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
   
env:
    ENVIRONMENT_TO_EXECUTE: Default
    REMOTE_GRID_URL: ${{ secrets.REMOTE_EXECUTION_URL}}
jobs:
  build:
   
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Setup Java 11
       - uses: actions/setup-java@v4
         with:
            distribution: 'temurin'
            java-version: '11'
     - name: Setup Permissions
       run: chmod -R 755 ./
     - name: Run CITS Test
       run: ./Run.command -run -project_location "Projects/Practice" -release "Release1" -testset "TestSet1" -setENV "run.ExecutionMode=Grid" -setENV "run.RemoteGridURL=$REMOTE_GRID_URL" -setENV "run.TestEnv=$ENVIRONMENT_TO_EXECUTE"
     - name: Upload Results
       - uses: actions/upload-artifact@v4
          with:
            name: Test Results
            path: Practice/Results/TestExecution/Release1/TestSet1/Latest
